<head>
	
	<style >

/*   table td
   {

   	border-color: red;
   	border-style: double;
   	
   }*/

	</style>
</head>

<div id="view-content">
	<p>View script for controller <b>forums</b> and script/action name <b>list</b></p>
</div>

<table class="table table-hover">
       <?php
       
for($i = 0; $i<count($this->forums); $i++){
     
?>
    <tr>
        <td  class="info" width='120px' height='60px'>
            <img src="../forum_images/<?php echo $this->forums[$i]['image'];?>" class="img-circle"  width="100" height="50px"/>
            
        </td>
    <td class="danger">
<a href="<?php echo $this->baseUrl()?>/threads/list/id/<?php echo $this->forums[$i]['id'];?>" class="text-danger"> <?php echo $this->forums[$i]["name"];?></a>
    </td>

 <td class="success" width='150px'>    
<a href="<?php echo $this->baseUrl()?>/forums/edit/id/<?php echo $this->forums[$i]['id'];?>" class="btn btn-success btn-lg" > Edit </a>

</td>

        <td class="warning" width='150px' >    
<a href="<?php echo $this->baseUrl()?>/forums/delete/id/<?php echo $this->forums[$i]['id'];?>/img/<?php echo $this->forums[$i]['image'];?>" class="btn btn-danger btn-lg" > Delete </a>

</td>

        <td class="active" width='150px' >    
<a href="<?php echo $this->baseUrl()?>/forums/lock/id/<?php echo $this->forums[$i]['id'];?>/lock/<?php echo $this->forums[$i]['is_locked'];?>" class="btn btn-warning btn-lg" > <?php if( $this->forums[$i]['is_locked'] == 0) echo "Lock"; else{ echo "Unlock";}?> </a>

</td>
    </tr>
<?php

}
?>
</table>